### ISSUE TITLE
Install git diff helper

### ISSUE THREAD

**Issue by pothos** [8051Enthusiast/biodiff#2]
When a `git-biodiff` executable is in the PATH, the user can run `git biodiff` instead of `git diff`.

The `git-biodiff` executable needs to run `git difftool --no-prompt --extcmd=biodiff` and pass all parameters along.

You can try this now by creating a `git-biodiff` bash script in your PATH:

```
#!/bin/sh
git difftool --no-prompt --extcmd=biodiff "$@"
```

For `cargo install` to set this up it would need to be implemented in Rust instead of bash and multiple binaries be defined in the `Cargo.toml` via `[[bin]]`. Edit: Wasn't even necessary with the autobin feature which is default in edition 2018.

**Comment by 8051Enthusiast** [comment]
Thank you, didn\t know this was possible. Played around with it in some firmware repositories and it works great.
