### ISSUE TITLE
New feature: Add Home, End shortcuts

### ISSUE THREAD

**Issue by Progress1** [8051Enthusiast/biodiff#5]
These shortcuts are very useful :) Also stop scrolling under negative offset, there is just black space and it's confusing. Tested on Win version.

**Comment by 8051Enthusiast** [comment]
the main branch now contains the bounds checking and the shortcuts (as well as some new display features, it is so fun to program these)

**Comment by Progress1** [comment]
Don't forget compile a new release ;-)

**Comment by 8051Enthusiast** [comment]
Did that just now, you can now download them (here)[https://github.com/8051Enthusiast/biodiff/releases/tag/v1.0.0].
