### ISSUE TITLE
Document alternate shortcuts for alignment

### ISSUE THREAD

**Issue by JamesB797** [8051Enthusiast/biodiff#7]
On Mac specifically the F keys are often captured by the OS for specific purposes such as Mission Control. I currently have them bound to F1: change desktop left, F2: change desktop right, F3: show all windows. So to use biodiff right now I need to change my keyboard settings and then change them back after.

It would be nice to have some alternate shortcuts that are less likely to be clobbered by OS settings. (Though it's not too hard to toggle the F3 shortcut in the OS settings).

Thanks! 

biodiff is very cool and really helpful for finding the differences. Bioinformatics algorithms are perfect for this sort of thing.

**Comment by 8051Enthusiast** [comment]
I already suspected there might be issues, which is why the regular number keys also work in place of the F keys.
I will leave this issue open for now as I still need to document this in the next version.
